### PR TITLE
Adds Alex Shadley function

### PR DESCRIPTION
**Pull request by alex4864**

### CODE REVIEW

**Comment by awarrington0895** [comment]
Hey Alex!  Thanks for jumping into this so quick.  I know it seems redundant to treat such simple code with such care, but avoid committing straight to master.  Instead, anytime you want to alter code within the repo you should create a branch to work within.  Once the branch is ready to be merged, submit a pull request to merge into master.  It makes it easier to check if your code has errors, and is safer in the long run.  

Refer to http://scottchacon.com/2011/08/31/github-flow.html for a more detailed explaination.

**Comment by alex4864** [comment]
I'm an absolute novice with git, sorry about that!  So to do this properly, should I create a branch on my fork, and then make a pull request that would add that branch to the master repo?

**Comment by alex4864** [comment]
The concept of forking still kinda confuses me

**Comment by awarrington0895** [comment]
Completely ok!  I've used git plenty, but I have never used it for collaboration.  It's a learning experience for everyone.  It looks like you DO need to be a collaborator.  I sent you an invite.  What you would do is CLONE the repo (not fork it), then create a branch for you to work within that won't affect the master branch.

After that go ahead and push that branch to Github (it lets everyone else know what you're working on).  From there just write the code you need to finish the branch, and then you will submit a pull request to merge your branch into master.  

Sorry for confusing you!  I'm still learning things too :)

**Pull request closed without merging**
